packageExtensions:
  parcel@*:
    peerDependencies:
      assert: "*"
      browserify-zlib: "*"
      buffer: "*"
      console-browserify: "*"
      constants-browserify: "*"
      crypto-browserify: "*"
      domain-browser: "*"
      events: "*"
      https-browserify: "*"
      os-browserify: "*"
      path-browserify: "*"
      process: "*"
      punycode: "*"
      querystring-es3: "*"
      stream-browserify: "*"
      stream-http: "*"
      string_decoder: "*"
      timers-browserify: "*"
      tty-browserify: "*"
      url: "*"
      util: "*"
      vm-browserify: "*"
  "@parcel/bundler-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/compressor-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/config-default@*":
    peerDependencies:
      "assert": "*"
      "browserify-zlib": "*"
      "buffer": "*"
      "console-browserify": "*"
      "constants-browserify": "*"
      "crypto-browserify": "*"
      "domain-browser": "*"
      "events": "*"
      "https-browserify": "*"
      "os-browserify": "*"
      "path-browserify": "*"
      "process": "*"
      "punycode": "*"
      "querystring-es3": "*"
      "stream-browserify": "*"
      "stream-http": "*"
      "string_decoder": "*"
      "timers-browserify": "*"
      "tty-browserify": "*"
      "url": "*"
      "util": "*"
      "vm-browserify": "*"
  "@parcel/config-webextension@*":
    peerDependencies:
      "assert": "*"
      "browserify-zlib": "*"
      "buffer": "*"
      "console-browserify": "*"
      "constants-browserify": "*"
      "crypto-browserify": "*"
      "domain-browser": "*"
      "events": "*"
      "https-browserify": "*"
      "os-browserify": "*"
      "path-browserify": "*"
      "process": "*"
      "punycode": "*"
      "querystring-es3": "*"
      "stream-browserify": "*"
      "stream-http": "*"
      "string_decoder": "*"
      "timers-browserify": "*"
      "tty-browserify": "*"
      "url": "*"
      "util": "*"
      "vm-browserify": "*"
  "@parcel/namer-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-css@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-htmlnano@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-image@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-svgo@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-terser@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-css@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-html@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-svg@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-webextension@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/plugin@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/reporter-cli@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/reporter-dev-server@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/resolver-default@*":
    peerDependencies:
      "@parcel/core": "*"
      assert: "*"
      browserify-zlib: "*"
      buffer: "*"
      console-browserify: "*"
      constants-browserify: "*"
      crypto-browserify: "*"
      domain-browser: "*"
      events: "*"
      https-browserify: "*"
      os-browserify: "*"
      path-browserify: "*"
      process: "*"
      punycode: "*"
      querystring-es3: "*"
      stream-browserify: "*"
      stream-http: "*"
      string_decoder: "*"
      timers-browserify: "*"
      tty-browserify: "*"
      url: "*"
      util: "*"
      vm-browserify: "*"
  "@parcel/runtime-browser-hmr@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-react-refresh@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-service-worker@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-webextension@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-babel@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-css@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-html@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-json@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-postcss@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-posthtml@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-react-refresh-wrap@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-svg@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-webextension@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
